export const CARD_STORE_NAMES = [
  "Ls Game Nerdz Inc.",
  "Common Ground Games",
  "Mystery Mtg",
  "Cardquest",
  "Hill Top Collectibles",
  "Trading Card World",
  "Opcg",
  "Cloud Collectibles",
  "Lspb",
  "Andyseous Odyssey",
  "Zenith Tcg",
  "Riot Games",
  "The Pokemon Company",
  "Boardwalk Games",
  "Mt Moon Collectibles",
];
